// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: dreamweave/v1/assets.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAssetServiceCompleteAssetUpload = "/dreamweave.v1.AssetService/CompleteAssetUpload"
const OperationAssetServiceCreateAssetUpload = "/dreamweave.v1.AssetService/CreateAssetUpload"
const OperationAssetServiceCreateWebAsset = "/dreamweave.v1.AssetService/CreateWebAsset"
const OperationAssetServiceGetDownloadAccess = "/dreamweave.v1.AssetService/GetDownloadAccess"
const OperationAssetServiceGetHtmlPreviewAccess = "/dreamweave.v1.AssetService/GetHtmlPreviewAccess"
const OperationAssetServiceGetPlaybackAccess = "/dreamweave.v1.AssetService/GetPlaybackAccess"
const OperationAssetServiceGetPreviewAccess = "/dreamweave.v1.AssetService/GetPreviewAccess"

type AssetServiceHTTPServer interface {
	CompleteAssetUpload(context.Context, *CompleteAssetUploadRequest) (*Asset, error)
	CreateAssetUpload(context.Context, *CreateAssetUploadRequest) (*AssetUploadTicket, error)
	CreateWebAsset(context.Context, *CreateWebAssetRequest) (*Asset, error)
	GetDownloadAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error)
	GetHtmlPreviewAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error)
	GetPlaybackAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error)
	GetPreviewAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error)
}

func RegisterAssetServiceHTTPServer(s *http.Server, srv AssetServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/dreamweave/v1/projects/{project_id}/asset-uploads", _AssetService_CreateAssetUpload0_HTTP_Handler(srv))
	r.POST("/api/dreamweave/v1/projects/{project_id}/asset-uploads/{upload_id}/complete", _AssetService_CompleteAssetUpload0_HTTP_Handler(srv))
	r.POST("/api/dreamweave/v1/projects/{project_id}/web-assets", _AssetService_CreateWebAsset0_HTTP_Handler(srv))
	r.POST("/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/preview-access", _AssetService_GetPreviewAccess0_HTTP_Handler(srv))
	r.POST("/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/download-access", _AssetService_GetDownloadAccess0_HTTP_Handler(srv))
	r.POST("/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/playback-access", _AssetService_GetPlaybackAccess0_HTTP_Handler(srv))
	r.POST("/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/html-preview-access", _AssetService_GetHtmlPreviewAccess0_HTTP_Handler(srv))
}

func _AssetService_CreateAssetUpload0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAssetUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceCreateAssetUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAssetUpload(ctx, req.(*CreateAssetUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssetUploadTicket)
		return ctx.Result(200, reply)
	}
}

func _AssetService_CompleteAssetUpload0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteAssetUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceCompleteAssetUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteAssetUpload(ctx, req.(*CompleteAssetUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Asset)
		return ctx.Result(200, reply)
	}
}

func _AssetService_CreateWebAsset0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWebAssetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceCreateWebAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWebAsset(ctx, req.(*CreateWebAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Asset)
		return ctx.Result(200, reply)
	}
}

func _AssetService_GetPreviewAccess0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAssetAccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceGetPreviewAccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPreviewAccess(ctx, req.(*GetAssetAccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssetAccess)
		return ctx.Result(200, reply)
	}
}

func _AssetService_GetDownloadAccess0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAssetAccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceGetDownloadAccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDownloadAccess(ctx, req.(*GetAssetAccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssetAccess)
		return ctx.Result(200, reply)
	}
}

func _AssetService_GetPlaybackAccess0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAssetAccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceGetPlaybackAccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPlaybackAccess(ctx, req.(*GetAssetAccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssetAccess)
		return ctx.Result(200, reply)
	}
}

func _AssetService_GetHtmlPreviewAccess0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAssetAccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceGetHtmlPreviewAccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHtmlPreviewAccess(ctx, req.(*GetAssetAccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssetAccess)
		return ctx.Result(200, reply)
	}
}

type AssetServiceHTTPClient interface {
	CompleteAssetUpload(ctx context.Context, req *CompleteAssetUploadRequest, opts ...http.CallOption) (rsp *Asset, err error)
	CreateAssetUpload(ctx context.Context, req *CreateAssetUploadRequest, opts ...http.CallOption) (rsp *AssetUploadTicket, err error)
	CreateWebAsset(ctx context.Context, req *CreateWebAssetRequest, opts ...http.CallOption) (rsp *Asset, err error)
	GetDownloadAccess(ctx context.Context, req *GetAssetAccessRequest, opts ...http.CallOption) (rsp *AssetAccess, err error)
	GetHtmlPreviewAccess(ctx context.Context, req *GetAssetAccessRequest, opts ...http.CallOption) (rsp *AssetAccess, err error)
	GetPlaybackAccess(ctx context.Context, req *GetAssetAccessRequest, opts ...http.CallOption) (rsp *AssetAccess, err error)
	GetPreviewAccess(ctx context.Context, req *GetAssetAccessRequest, opts ...http.CallOption) (rsp *AssetAccess, err error)
}

type AssetServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAssetServiceHTTPClient(client *http.Client) AssetServiceHTTPClient {
	return &AssetServiceHTTPClientImpl{client}
}

func (c *AssetServiceHTTPClientImpl) CompleteAssetUpload(ctx context.Context, in *CompleteAssetUploadRequest, opts ...http.CallOption) (*Asset, error) {
	var out Asset
	pattern := "/api/dreamweave/v1/projects/{project_id}/asset-uploads/{upload_id}/complete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceCompleteAssetUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) CreateAssetUpload(ctx context.Context, in *CreateAssetUploadRequest, opts ...http.CallOption) (*AssetUploadTicket, error) {
	var out AssetUploadTicket
	pattern := "/api/dreamweave/v1/projects/{project_id}/asset-uploads"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceCreateAssetUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) CreateWebAsset(ctx context.Context, in *CreateWebAssetRequest, opts ...http.CallOption) (*Asset, error) {
	var out Asset
	pattern := "/api/dreamweave/v1/projects/{project_id}/web-assets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceCreateWebAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) GetDownloadAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...http.CallOption) (*AssetAccess, error) {
	var out AssetAccess
	pattern := "/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/download-access"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceGetDownloadAccess))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) GetHtmlPreviewAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...http.CallOption) (*AssetAccess, error) {
	var out AssetAccess
	pattern := "/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/html-preview-access"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceGetHtmlPreviewAccess))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) GetPlaybackAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...http.CallOption) (*AssetAccess, error) {
	var out AssetAccess
	pattern := "/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/playback-access"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceGetPlaybackAccess))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) GetPreviewAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...http.CallOption) (*AssetAccess, error) {
	var out AssetAccess
	pattern := "/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/preview-access"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceGetPreviewAccess))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
