// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: dreamweave/v1/assets.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAssetUploadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectId        string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FileName         string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	DeclaredMimeType string                 `protobuf:"bytes,3,opt,name=declared_mime_type,json=declaredMimeType,proto3" json:"declared_mime_type,omitempty"`
	ByteSize         int64                  `protobuf:"varint,4,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAssetUploadRequest) Reset() {
	*x = CreateAssetUploadRequest{}
	mi := &file_dreamweave_v1_assets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetUploadRequest) ProtoMessage() {}

func (x *CreateAssetUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_assets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetUploadRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetUploadRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_assets_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAssetUploadRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateAssetUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateAssetUploadRequest) GetDeclaredMimeType() string {
	if x != nil {
		return x.DeclaredMimeType
	}
	return ""
}

func (x *CreateAssetUploadRequest) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

type AssetUploadTicket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadId        string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	UploadUrl       string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Method          string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	RequiredHeaders map[string]string      `protobuf:"bytes,4,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt       string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssetUploadTicket) Reset() {
	*x = AssetUploadTicket{}
	mi := &file_dreamweave_v1_assets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetUploadTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetUploadTicket) ProtoMessage() {}

func (x *AssetUploadTicket) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_assets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetUploadTicket.ProtoReflect.Descriptor instead.
func (*AssetUploadTicket) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_assets_proto_rawDescGZIP(), []int{1}
}

func (x *AssetUploadTicket) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *AssetUploadTicket) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *AssetUploadTicket) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AssetUploadTicket) GetRequiredHeaders() map[string]string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *AssetUploadTicket) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type CompleteAssetUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAssetUploadRequest) Reset() {
	*x = CompleteAssetUploadRequest{}
	mi := &file_dreamweave_v1_assets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAssetUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAssetUploadRequest) ProtoMessage() {}

func (x *CompleteAssetUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_assets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAssetUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteAssetUploadRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_assets_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteAssetUploadRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CompleteAssetUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type CreateWebAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebAssetRequest) Reset() {
	*x = CreateWebAssetRequest{}
	mi := &file_dreamweave_v1_assets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebAssetRequest) ProtoMessage() {}

func (x *CreateWebAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_assets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateWebAssetRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_assets_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWebAssetRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateWebAssetRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateWebAssetRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type Asset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Kind            string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	DisplayName     string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ProcessingState string                 `protobuf:"bytes,5,opt,name=processing_state,json=processingState,proto3" json:"processing_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_dreamweave_v1_assets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_assets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_assets_proto_rawDescGZIP(), []int{4}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Asset) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Asset) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Asset) GetProcessingState() string {
	if x != nil {
		return x.ProcessingState
	}
	return ""
}

type GetAssetAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetAccessRequest) Reset() {
	*x = GetAssetAccessRequest{}
	mi := &file_dreamweave_v1_assets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetAccessRequest) ProtoMessage() {}

func (x *GetAssetAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_assets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetAccessRequest.ProtoReflect.Descriptor instead.
func (*GetAssetAccessRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_assets_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssetAccessRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetAssetAccessRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type AssetAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetAccess) Reset() {
	*x = AssetAccess{}
	mi := &file_dreamweave_v1_assets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetAccess) ProtoMessage() {}

func (x *AssetAccess) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_assets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetAccess.ProtoReflect.Descriptor instead.
func (*AssetAccess) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_assets_proto_rawDescGZIP(), []int{6}
}

func (x *AssetAccess) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AssetAccess) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AssetAccess) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_dreamweave_v1_assets_proto protoreflect.FileDescriptor

const file_dreamweave_v1_assets_proto_rawDesc = "" +
	"\n" +
	"\x1adreamweave/v1/assets.proto\x12\rdreamweave.v1\x1a\x1cgoogle/api/annotations.proto\"\xa1\x01\n" +
	"\x18CreateAssetUploadRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12,\n" +
	"\x12declared_mime_type\x18\x03 \x01(\tR\x10declaredMimeType\x12\x1b\n" +
	"\tbyte_size\x18\x04 \x01(\x03R\bbyteSize\"\xac\x02\n" +
	"\x11AssetUploadTicket\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12`\n" +
	"\x10required_headers\x18\x04 \x03(\v25.dreamweave.v1.AssetUploadTicket.RequiredHeadersEntryR\x0frequiredHeaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\x1aB\n" +
	"\x14RequiredHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x1aCompleteAssetUploadRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"k\n" +
	"\x15CreateWebAssetRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"\x98\x01\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12)\n" +
	"\x10processing_state\x18\x05 \x01(\tR\x0fprocessingState\"Q\n" +
	"\x15GetAssetAccessRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"[\n" +
	"\vAssetAccess\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName2\xb3\t\n" +
	"\fAssetService\x12\xa1\x01\n" +
	"\x11CreateAssetUpload\x12'.dreamweave.v1.CreateAssetUploadRequest\x1a .dreamweave.v1.AssetUploadTicket\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/api/dreamweave/v1/projects/{project_id}/asset-uploads\x12\xae\x01\n" +
	"\x13CompleteAssetUpload\x12).dreamweave.v1.CompleteAssetUploadRequest\x1a\x14.dreamweave.v1.Asset\"V\x82\xd3\xe4\x93\x02P:\x01*\"K/api/dreamweave/v1/projects/{project_id}/asset-uploads/{upload_id}/complete\x12\x8c\x01\n" +
	"\x0eCreateWebAsset\x12$.dreamweave.v1.CreateWebAssetRequest\x1a\x14.dreamweave.v1.Asset\">\x82\xd3\xe4\x93\x028:\x01*\"3/api/dreamweave/v1/projects/{project_id}/web-assets\x12\xaa\x01\n" +
	"\x10GetPreviewAccess\x12$.dreamweave.v1.GetAssetAccessRequest\x1a\x1a.dreamweave.v1.AssetAccess\"T\x82\xd3\xe4\x93\x02N:\x01*\"I/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/preview-access\x12\xac\x01\n" +
	"\x11GetDownloadAccess\x12$.dreamweave.v1.GetAssetAccessRequest\x1a\x1a.dreamweave.v1.AssetAccess\"U\x82\xd3\xe4\x93\x02O:\x01*\"J/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/download-access\x12\xac\x01\n" +
	"\x11GetPlaybackAccess\x12$.dreamweave.v1.GetAssetAccessRequest\x1a\x1a.dreamweave.v1.AssetAccess\"U\x82\xd3\xe4\x93\x02O:\x01*\"J/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/playback-access\x12\xb3\x01\n" +
	"\x14GetHtmlPreviewAccess\x12$.dreamweave.v1.GetAssetAccessRequest\x1a\x1a.dreamweave.v1.AssetAccess\"Y\x82\xd3\xe4\x93\x02S:\x01*\"N/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/html-preview-accessBEZCgithub.com/dream-weave/dream-weave/apps/server/api/dreamweave/v1;v1b\x06proto3"

var (
	file_dreamweave_v1_assets_proto_rawDescOnce sync.Once
	file_dreamweave_v1_assets_proto_rawDescData []byte
)

func file_dreamweave_v1_assets_proto_rawDescGZIP() []byte {
	file_dreamweave_v1_assets_proto_rawDescOnce.Do(func() {
		file_dreamweave_v1_assets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dreamweave_v1_assets_proto_rawDesc), len(file_dreamweave_v1_assets_proto_rawDesc)))
	})
	return file_dreamweave_v1_assets_proto_rawDescData
}

var file_dreamweave_v1_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dreamweave_v1_assets_proto_goTypes = []any{
	(*CreateAssetUploadRequest)(nil),   // 0: dreamweave.v1.CreateAssetUploadRequest
	(*AssetUploadTicket)(nil),          // 1: dreamweave.v1.AssetUploadTicket
	(*CompleteAssetUploadRequest)(nil), // 2: dreamweave.v1.CompleteAssetUploadRequest
	(*CreateWebAssetRequest)(nil),      // 3: dreamweave.v1.CreateWebAssetRequest
	(*Asset)(nil),                      // 4: dreamweave.v1.Asset
	(*GetAssetAccessRequest)(nil),      // 5: dreamweave.v1.GetAssetAccessRequest
	(*AssetAccess)(nil),                // 6: dreamweave.v1.AssetAccess
	nil,                                // 7: dreamweave.v1.AssetUploadTicket.RequiredHeadersEntry
}
var file_dreamweave_v1_assets_proto_depIdxs = []int32{
	7, // 0: dreamweave.v1.AssetUploadTicket.required_headers:type_name -> dreamweave.v1.AssetUploadTicket.RequiredHeadersEntry
	0, // 1: dreamweave.v1.AssetService.CreateAssetUpload:input_type -> dreamweave.v1.CreateAssetUploadRequest
	2, // 2: dreamweave.v1.AssetService.CompleteAssetUpload:input_type -> dreamweave.v1.CompleteAssetUploadRequest
	3, // 3: dreamweave.v1.AssetService.CreateWebAsset:input_type -> dreamweave.v1.CreateWebAssetRequest
	5, // 4: dreamweave.v1.AssetService.GetPreviewAccess:input_type -> dreamweave.v1.GetAssetAccessRequest
	5, // 5: dreamweave.v1.AssetService.GetDownloadAccess:input_type -> dreamweave.v1.GetAssetAccessRequest
	5, // 6: dreamweave.v1.AssetService.GetPlaybackAccess:input_type -> dreamweave.v1.GetAssetAccessRequest
	5, // 7: dreamweave.v1.AssetService.GetHtmlPreviewAccess:input_type -> dreamweave.v1.GetAssetAccessRequest
	1, // 8: dreamweave.v1.AssetService.CreateAssetUpload:output_type -> dreamweave.v1.AssetUploadTicket
	4, // 9: dreamweave.v1.AssetService.CompleteAssetUpload:output_type -> dreamweave.v1.Asset
	4, // 10: dreamweave.v1.AssetService.CreateWebAsset:output_type -> dreamweave.v1.Asset
	6, // 11: dreamweave.v1.AssetService.GetPreviewAccess:output_type -> dreamweave.v1.AssetAccess
	6, // 12: dreamweave.v1.AssetService.GetDownloadAccess:output_type -> dreamweave.v1.AssetAccess
	6, // 13: dreamweave.v1.AssetService.GetPlaybackAccess:output_type -> dreamweave.v1.AssetAccess
	6, // 14: dreamweave.v1.AssetService.GetHtmlPreviewAccess:output_type -> dreamweave.v1.AssetAccess
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dreamweave_v1_assets_proto_init() }
func file_dreamweave_v1_assets_proto_init() {
	if File_dreamweave_v1_assets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dreamweave_v1_assets_proto_rawDesc), len(file_dreamweave_v1_assets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dreamweave_v1_assets_proto_goTypes,
		DependencyIndexes: file_dreamweave_v1_assets_proto_depIdxs,
		MessageInfos:      file_dreamweave_v1_assets_proto_msgTypes,
	}.Build()
	File_dreamweave_v1_assets_proto = out.File
	file_dreamweave_v1_assets_proto_goTypes = nil
	file_dreamweave_v1_assets_proto_depIdxs = nil
}
