// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dreamweave/v1/assets.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetService_CreateAssetUpload_FullMethodName    = "/dreamweave.v1.AssetService/CreateAssetUpload"
	AssetService_CompleteAssetUpload_FullMethodName  = "/dreamweave.v1.AssetService/CompleteAssetUpload"
	AssetService_CreateWebAsset_FullMethodName       = "/dreamweave.v1.AssetService/CreateWebAsset"
	AssetService_GetPreviewAccess_FullMethodName     = "/dreamweave.v1.AssetService/GetPreviewAccess"
	AssetService_GetDownloadAccess_FullMethodName    = "/dreamweave.v1.AssetService/GetDownloadAccess"
	AssetService_GetPlaybackAccess_FullMethodName    = "/dreamweave.v1.AssetService/GetPlaybackAccess"
	AssetService_GetHtmlPreviewAccess_FullMethodName = "/dreamweave.v1.AssetService/GetHtmlPreviewAccess"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetServiceClient interface {
	CreateAssetUpload(ctx context.Context, in *CreateAssetUploadRequest, opts ...grpc.CallOption) (*AssetUploadTicket, error)
	CompleteAssetUpload(ctx context.Context, in *CompleteAssetUploadRequest, opts ...grpc.CallOption) (*Asset, error)
	CreateWebAsset(ctx context.Context, in *CreateWebAssetRequest, opts ...grpc.CallOption) (*Asset, error)
	GetPreviewAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...grpc.CallOption) (*AssetAccess, error)
	GetDownloadAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...grpc.CallOption) (*AssetAccess, error)
	GetPlaybackAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...grpc.CallOption) (*AssetAccess, error)
	GetHtmlPreviewAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...grpc.CallOption) (*AssetAccess, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) CreateAssetUpload(ctx context.Context, in *CreateAssetUploadRequest, opts ...grpc.CallOption) (*AssetUploadTicket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetUploadTicket)
	err := c.cc.Invoke(ctx, AssetService_CreateAssetUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CompleteAssetUpload(ctx context.Context, in *CompleteAssetUploadRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_CompleteAssetUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CreateWebAsset(ctx context.Context, in *CreateWebAssetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_CreateWebAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetPreviewAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...grpc.CallOption) (*AssetAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetAccess)
	err := c.cc.Invoke(ctx, AssetService_GetPreviewAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetDownloadAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...grpc.CallOption) (*AssetAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetAccess)
	err := c.cc.Invoke(ctx, AssetService_GetDownloadAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetPlaybackAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...grpc.CallOption) (*AssetAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetAccess)
	err := c.cc.Invoke(ctx, AssetService_GetPlaybackAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetHtmlPreviewAccess(ctx context.Context, in *GetAssetAccessRequest, opts ...grpc.CallOption) (*AssetAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetAccess)
	err := c.cc.Invoke(ctx, AssetService_GetHtmlPreviewAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
type AssetServiceServer interface {
	CreateAssetUpload(context.Context, *CreateAssetUploadRequest) (*AssetUploadTicket, error)
	CompleteAssetUpload(context.Context, *CompleteAssetUploadRequest) (*Asset, error)
	CreateWebAsset(context.Context, *CreateWebAssetRequest) (*Asset, error)
	GetPreviewAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error)
	GetDownloadAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error)
	GetPlaybackAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error)
	GetHtmlPreviewAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) CreateAssetUpload(context.Context, *CreateAssetUploadRequest) (*AssetUploadTicket, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssetUpload not implemented")
}
func (UnimplementedAssetServiceServer) CompleteAssetUpload(context.Context, *CompleteAssetUploadRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteAssetUpload not implemented")
}
func (UnimplementedAssetServiceServer) CreateWebAsset(context.Context, *CreateWebAssetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWebAsset not implemented")
}
func (UnimplementedAssetServiceServer) GetPreviewAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreviewAccess not implemented")
}
func (UnimplementedAssetServiceServer) GetDownloadAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDownloadAccess not implemented")
}
func (UnimplementedAssetServiceServer) GetPlaybackAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaybackAccess not implemented")
}
func (UnimplementedAssetServiceServer) GetHtmlPreviewAccess(context.Context, *GetAssetAccessRequest) (*AssetAccess, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHtmlPreviewAccess not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_CreateAssetUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CreateAssetUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CreateAssetUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CreateAssetUpload(ctx, req.(*CreateAssetUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CompleteAssetUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAssetUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CompleteAssetUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CompleteAssetUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CompleteAssetUpload(ctx, req.(*CompleteAssetUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CreateWebAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CreateWebAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CreateWebAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CreateWebAsset(ctx, req.(*CreateWebAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetPreviewAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetPreviewAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetPreviewAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetPreviewAccess(ctx, req.(*GetAssetAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetDownloadAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetDownloadAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetDownloadAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetDownloadAccess(ctx, req.(*GetAssetAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetPlaybackAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetPlaybackAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetPlaybackAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetPlaybackAccess(ctx, req.(*GetAssetAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetHtmlPreviewAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetHtmlPreviewAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetHtmlPreviewAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetHtmlPreviewAccess(ctx, req.(*GetAssetAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dreamweave.v1.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssetUpload",
			Handler:    _AssetService_CreateAssetUpload_Handler,
		},
		{
			MethodName: "CompleteAssetUpload",
			Handler:    _AssetService_CompleteAssetUpload_Handler,
		},
		{
			MethodName: "CreateWebAsset",
			Handler:    _AssetService_CreateWebAsset_Handler,
		},
		{
			MethodName: "GetPreviewAccess",
			Handler:    _AssetService_GetPreviewAccess_Handler,
		},
		{
			MethodName: "GetDownloadAccess",
			Handler:    _AssetService_GetDownloadAccess_Handler,
		},
		{
			MethodName: "GetPlaybackAccess",
			Handler:    _AssetService_GetPlaybackAccess_Handler,
		},
		{
			MethodName: "GetHtmlPreviewAccess",
			Handler:    _AssetService_GetHtmlPreviewAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dreamweave/v1/assets.proto",
}
