// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: dreamweave/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_dreamweave_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSessionRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CurrentPrincipal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentPrincipal) Reset() {
	*x = CurrentPrincipal{}
	mi := &file_dreamweave_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentPrincipal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentPrincipal) ProtoMessage() {}

func (x *CurrentPrincipal) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentPrincipal.ProtoReflect.Descriptor instead.
func (*CurrentPrincipal) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentPrincipal) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CurrentPrincipal) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_dreamweave_v1_auth_proto protoreflect.FileDescriptor

const file_dreamweave_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18dreamweave/v1/auth.proto\x12\rdreamweave.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"H\n" +
	"\x14CreateSessionRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"A\n" +
	"\x10CurrentPrincipal\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\x8c\x02\n" +
	"\vAuthService\x12\x82\x01\n" +
	"\rCreateSession\x12#.dreamweave.v1.CreateSessionRequest\x1a\x1f.dreamweave.v1.CurrentPrincipal\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/dreamweave/v1/auth/sessions\x12x\n" +
	"\x14DeleteCurrentSession\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"0\x82\xd3\xe4\x93\x02**(/api/dreamweave/v1/auth/sessions/currentBEZCgithub.com/dream-weave/dream-weave/apps/server/api/dreamweave/v1;v1b\x06proto3"

var (
	file_dreamweave_v1_auth_proto_rawDescOnce sync.Once
	file_dreamweave_v1_auth_proto_rawDescData []byte
)

func file_dreamweave_v1_auth_proto_rawDescGZIP() []byte {
	file_dreamweave_v1_auth_proto_rawDescOnce.Do(func() {
		file_dreamweave_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dreamweave_v1_auth_proto_rawDesc), len(file_dreamweave_v1_auth_proto_rawDesc)))
	})
	return file_dreamweave_v1_auth_proto_rawDescData
}

var file_dreamweave_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dreamweave_v1_auth_proto_goTypes = []any{
	(*CreateSessionRequest)(nil), // 0: dreamweave.v1.CreateSessionRequest
	(*CurrentPrincipal)(nil),     // 1: dreamweave.v1.CurrentPrincipal
	(*emptypb.Empty)(nil),        // 2: google.protobuf.Empty
}
var file_dreamweave_v1_auth_proto_depIdxs = []int32{
	0, // 0: dreamweave.v1.AuthService.CreateSession:input_type -> dreamweave.v1.CreateSessionRequest
	2, // 1: dreamweave.v1.AuthService.DeleteCurrentSession:input_type -> google.protobuf.Empty
	1, // 2: dreamweave.v1.AuthService.CreateSession:output_type -> dreamweave.v1.CurrentPrincipal
	2, // 3: dreamweave.v1.AuthService.DeleteCurrentSession:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dreamweave_v1_auth_proto_init() }
func file_dreamweave_v1_auth_proto_init() {
	if File_dreamweave_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dreamweave_v1_auth_proto_rawDesc), len(file_dreamweave_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dreamweave_v1_auth_proto_goTypes,
		DependencyIndexes: file_dreamweave_v1_auth_proto_depIdxs,
		MessageInfos:      file_dreamweave_v1_auth_proto_msgTypes,
	}.Build()
	File_dreamweave_v1_auth_proto = out.File
	file_dreamweave_v1_auth_proto_goTypes = nil
	file_dreamweave_v1_auth_proto_depIdxs = nil
}
