// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: dreamweave/v1/canvas.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Placement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64                `protobuf:"fixed64,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,5,opt,name=height,proto3" json:"height,omitempty"`
	ZIndex        int32                  `protobuf:"varint,6,opt,name=z_index,json=zIndex,proto3" json:"z_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placement) Reset() {
	*x = Placement{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placement) ProtoMessage() {}

func (x *Placement) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placement.ProtoReflect.Descriptor instead.
func (*Placement) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{0}
}

func (x *Placement) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Placement) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Placement) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Placement) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Placement) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Placement) GetZIndex() int32 {
	if x != nil {
		return x.ZIndex
	}
	return 0
}

type CanvasConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	SourceHandle  string                 `protobuf:"bytes,3,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,4,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	TargetHandle  string                 `protobuf:"bytes,5,opt,name=target_handle,json=targetHandle,proto3" json:"target_handle,omitempty"`
	Shape         string                 `protobuf:"bytes,6,opt,name=shape,proto3" json:"shape,omitempty"`
	Stroke        string                 `protobuf:"bytes,7,opt,name=stroke,proto3" json:"stroke,omitempty"`
	Direction     string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	SourceX       float64                `protobuf:"fixed64,9,opt,name=source_x,json=sourceX,proto3" json:"source_x,omitempty"`
	SourceY       float64                `protobuf:"fixed64,10,opt,name=source_y,json=sourceY,proto3" json:"source_y,omitempty"`
	TargetX       float64                `protobuf:"fixed64,11,opt,name=target_x,json=targetX,proto3" json:"target_x,omitempty"`
	TargetY       float64                `protobuf:"fixed64,12,opt,name=target_y,json=targetY,proto3" json:"target_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasConnection) Reset() {
	*x = CanvasConnection{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasConnection) ProtoMessage() {}

func (x *CanvasConnection) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasConnection.ProtoReflect.Descriptor instead.
func (*CanvasConnection) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{1}
}

func (x *CanvasConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CanvasConnection) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *CanvasConnection) GetSourceHandle() string {
	if x != nil {
		return x.SourceHandle
	}
	return ""
}

func (x *CanvasConnection) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *CanvasConnection) GetTargetHandle() string {
	if x != nil {
		return x.TargetHandle
	}
	return ""
}

func (x *CanvasConnection) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *CanvasConnection) GetStroke() string {
	if x != nil {
		return x.Stroke
	}
	return ""
}

func (x *CanvasConnection) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CanvasConnection) GetSourceX() float64 {
	if x != nil {
		return x.SourceX
	}
	return 0
}

func (x *CanvasConnection) GetSourceY() float64 {
	if x != nil {
		return x.SourceY
	}
	return 0
}

func (x *CanvasConnection) GetTargetX() float64 {
	if x != nil {
		return x.TargetX
	}
	return 0
}

func (x *CanvasConnection) GetTargetY() float64 {
	if x != nil {
		return x.TargetY
	}
	return 0
}

type FrameData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{2}
}

func (x *FrameData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FrameData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FrameData) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type GetCanvasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCanvasRequest) Reset() {
	*x = GetCanvasRequest{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCanvasRequest) ProtoMessage() {}

func (x *GetCanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCanvasRequest.ProtoReflect.Descriptor instead.
func (*GetCanvasRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{3}
}

func (x *GetCanvasRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type MarkdownRenderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markdown      string                 `protobuf:"bytes,1,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkdownRenderData) Reset() {
	*x = MarkdownRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkdownRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkdownRenderData) ProtoMessage() {}

func (x *MarkdownRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkdownRenderData.ProtoReflect.Descriptor instead.
func (*MarkdownRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{4}
}

func (x *MarkdownRenderData) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type ImageRenderData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PreviewAvailable bool                   `protobuf:"varint,1,opt,name=preview_available,json=previewAvailable,proto3" json:"preview_available,omitempty"`
	Format           string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImageRenderData) Reset() {
	*x = ImageRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRenderData) ProtoMessage() {}

func (x *ImageRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRenderData.ProtoReflect.Descriptor instead.
func (*ImageRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{5}
}

func (x *ImageRenderData) GetPreviewAvailable() bool {
	if x != nil {
		return x.PreviewAvailable
	}
	return false
}

func (x *ImageRenderData) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type AudioRenderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	DurationMs    int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Waveform      []float64              `protobuf:"fixed64,3,rep,packed,name=waveform,proto3" json:"waveform,omitempty"`
	SceneLabel    string                 `protobuf:"bytes,4,opt,name=scene_label,json=sceneLabel,proto3" json:"scene_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioRenderData) Reset() {
	*x = AudioRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRenderData) ProtoMessage() {}

func (x *AudioRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRenderData.ProtoReflect.Descriptor instead.
func (*AudioRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{6}
}

func (x *AudioRenderData) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AudioRenderData) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AudioRenderData) GetWaveform() []float64 {
	if x != nil {
		return x.Waveform
	}
	return nil
}

func (x *AudioRenderData) GetSceneLabel() string {
	if x != nil {
		return x.SceneLabel
	}
	return ""
}

type VideoRenderData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PosterAvailable bool                   `protobuf:"varint,1,opt,name=poster_available,json=posterAvailable,proto3" json:"poster_available,omitempty"`
	DurationMs      int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ShotLabel       string                 `protobuf:"bytes,3,opt,name=shot_label,json=shotLabel,proto3" json:"shot_label,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoRenderData) Reset() {
	*x = VideoRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRenderData) ProtoMessage() {}

func (x *VideoRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRenderData.ProtoReflect.Descriptor instead.
func (*VideoRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{7}
}

func (x *VideoRenderData) GetPosterAvailable() bool {
	if x != nil {
		return x.PosterAvailable
	}
	return false
}

func (x *VideoRenderData) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *VideoRenderData) GetShotLabel() string {
	if x != nil {
		return x.ShotLabel
	}
	return ""
}

type WebRenderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Embeddable    bool                   `protobuf:"varint,2,opt,name=embeddable,proto3" json:"embeddable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRenderData) Reset() {
	*x = WebRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRenderData) ProtoMessage() {}

func (x *WebRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRenderData.ProtoReflect.Descriptor instead.
func (*WebRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{8}
}

func (x *WebRenderData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebRenderData) GetEmbeddable() bool {
	if x != nil {
		return x.Embeddable
	}
	return false
}

type HtmlRenderData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PreviewAvailable bool                   `protobuf:"varint,1,opt,name=preview_available,json=previewAvailable,proto3" json:"preview_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HtmlRenderData) Reset() {
	*x = HtmlRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HtmlRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HtmlRenderData) ProtoMessage() {}

func (x *HtmlRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HtmlRenderData.ProtoReflect.Descriptor instead.
func (*HtmlRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{9}
}

func (x *HtmlRenderData) GetPreviewAvailable() bool {
	if x != nil {
		return x.PreviewAvailable
	}
	return false
}

type PdfRenderData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PreviewAvailable bool                   `protobuf:"varint,1,opt,name=preview_available,json=previewAvailable,proto3" json:"preview_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PdfRenderData) Reset() {
	*x = PdfRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfRenderData) ProtoMessage() {}

func (x *PdfRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfRenderData.ProtoReflect.Descriptor instead.
func (*PdfRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{10}
}

func (x *PdfRenderData) GetPreviewAvailable() bool {
	if x != nil {
		return x.PreviewAvailable
	}
	return false
}

type OfficeRenderData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OfficeKind       string                 `protobuf:"bytes,1,opt,name=office_kind,json=officeKind,proto3" json:"office_kind,omitempty"`
	FileType         string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	PreviewAvailable bool                   `protobuf:"varint,3,opt,name=preview_available,json=previewAvailable,proto3" json:"preview_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OfficeRenderData) Reset() {
	*x = OfficeRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfficeRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeRenderData) ProtoMessage() {}

func (x *OfficeRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeRenderData.ProtoReflect.Descriptor instead.
func (*OfficeRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{11}
}

func (x *OfficeRenderData) GetOfficeKind() string {
	if x != nil {
		return x.OfficeKind
	}
	return ""
}

func (x *OfficeRenderData) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *OfficeRenderData) GetPreviewAvailable() bool {
	if x != nil {
		return x.PreviewAvailable
	}
	return false
}

type FrameRenderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRenderData) Reset() {
	*x = FrameRenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRenderData) ProtoMessage() {}

func (x *FrameRenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRenderData.ProtoReflect.Descriptor instead.
func (*FrameRenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{12}
}

func (x *FrameRenderData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FrameRenderData) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type RenderData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*RenderData_Markdown
	//	*RenderData_Image
	//	*RenderData_Audio
	//	*RenderData_Video
	//	*RenderData_WebPreview
	//	*RenderData_Html
	//	*RenderData_Pdf
	//	*RenderData_Office
	//	*RenderData_Frame
	Value         isRenderData_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderData) Reset() {
	*x = RenderData{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderData) ProtoMessage() {}

func (x *RenderData) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderData.ProtoReflect.Descriptor instead.
func (*RenderData) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{13}
}

func (x *RenderData) GetValue() isRenderData_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RenderData) GetMarkdown() *MarkdownRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_Markdown); ok {
			return x.Markdown
		}
	}
	return nil
}

func (x *RenderData) GetImage() *ImageRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *RenderData) GetAudio() *AudioRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *RenderData) GetVideo() *VideoRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *RenderData) GetWebPreview() *WebRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_WebPreview); ok {
			return x.WebPreview
		}
	}
	return nil
}

func (x *RenderData) GetHtml() *HtmlRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_Html); ok {
			return x.Html
		}
	}
	return nil
}

func (x *RenderData) GetPdf() *PdfRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_Pdf); ok {
			return x.Pdf
		}
	}
	return nil
}

func (x *RenderData) GetOffice() *OfficeRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_Office); ok {
			return x.Office
		}
	}
	return nil
}

func (x *RenderData) GetFrame() *FrameRenderData {
	if x != nil {
		if x, ok := x.Value.(*RenderData_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

type isRenderData_Value interface {
	isRenderData_Value()
}

type RenderData_Markdown struct {
	Markdown *MarkdownRenderData `protobuf:"bytes,1,opt,name=markdown,proto3,oneof"`
}

type RenderData_Image struct {
	Image *ImageRenderData `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type RenderData_Audio struct {
	Audio *AudioRenderData `protobuf:"bytes,3,opt,name=audio,proto3,oneof"`
}

type RenderData_Video struct {
	Video *VideoRenderData `protobuf:"bytes,4,opt,name=video,proto3,oneof"`
}

type RenderData_WebPreview struct {
	WebPreview *WebRenderData `protobuf:"bytes,5,opt,name=web_preview,json=webPreview,proto3,oneof"`
}

type RenderData_Html struct {
	Html *HtmlRenderData `protobuf:"bytes,6,opt,name=html,proto3,oneof"`
}

type RenderData_Pdf struct {
	Pdf *PdfRenderData `protobuf:"bytes,7,opt,name=pdf,proto3,oneof"`
}

type RenderData_Office struct {
	Office *OfficeRenderData `protobuf:"bytes,8,opt,name=office,proto3,oneof"`
}

type RenderData_Frame struct {
	Frame *FrameRenderData `protobuf:"bytes,10,opt,name=frame,proto3,oneof"`
}

func (*RenderData_Markdown) isRenderData_Value() {}

func (*RenderData_Image) isRenderData_Value() {}

func (*RenderData_Audio) isRenderData_Value() {}

func (*RenderData_Video) isRenderData_Value() {}

func (*RenderData_WebPreview) isRenderData_Value() {}

func (*RenderData_Html) isRenderData_Value() {}

func (*RenderData_Pdf) isRenderData_Value() {}

func (*RenderData_Office) isRenderData_Value() {}

func (*RenderData_Frame) isRenderData_Value() {}

type CanvasNodeSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	AssetId       string                 `protobuf:"bytes,5,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	RenderData    *RenderData            `protobuf:"bytes,6,opt,name=render_data,json=renderData,proto3" json:"render_data,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasNodeSnapshot) Reset() {
	*x = CanvasNodeSnapshot{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasNodeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasNodeSnapshot) ProtoMessage() {}

func (x *CanvasNodeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasNodeSnapshot.ProtoReflect.Descriptor instead.
func (*CanvasNodeSnapshot) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{14}
}

func (x *CanvasNodeSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CanvasNodeSnapshot) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CanvasNodeSnapshot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CanvasNodeSnapshot) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CanvasNodeSnapshot) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CanvasNodeSnapshot) GetRenderData() *RenderData {
	if x != nil {
		return x.RenderData
	}
	return nil
}

func (x *CanvasNodeSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CanvasNodeSnapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CanvasDocumentSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Nodes         []*CanvasNodeSnapshot  `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Placements    []*Placement           `protobuf:"bytes,4,rep,name=placements,proto3" json:"placements,omitempty"`
	Connections   []*CanvasConnection    `protobuf:"bytes,5,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasDocumentSnapshot) Reset() {
	*x = CanvasDocumentSnapshot{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasDocumentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasDocumentSnapshot) ProtoMessage() {}

func (x *CanvasDocumentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasDocumentSnapshot.ProtoReflect.Descriptor instead.
func (*CanvasDocumentSnapshot) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{15}
}

func (x *CanvasDocumentSnapshot) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CanvasDocumentSnapshot) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CanvasDocumentSnapshot) GetNodes() []*CanvasNodeSnapshot {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CanvasDocumentSnapshot) GetPlacements() []*Placement {
	if x != nil {
		return x.Placements
	}
	return nil
}

func (x *CanvasDocumentSnapshot) GetConnections() []*CanvasConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type CreateMarkdownNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Markdown      string                 `protobuf:"bytes,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Placement     *Placement             `protobuf:"bytes,3,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMarkdownNode) Reset() {
	*x = CreateMarkdownNode{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMarkdownNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarkdownNode) ProtoMessage() {}

func (x *CreateMarkdownNode) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarkdownNode.ProtoReflect.Descriptor instead.
func (*CreateMarkdownNode) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{16}
}

func (x *CreateMarkdownNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateMarkdownNode) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *CreateMarkdownNode) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

type UpdateMarkdownNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Markdown      string                 `protobuf:"bytes,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMarkdownNode) Reset() {
	*x = UpdateMarkdownNode{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMarkdownNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMarkdownNode) ProtoMessage() {}

func (x *UpdateMarkdownNode) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMarkdownNode.ProtoReflect.Descriptor instead.
func (*UpdateMarkdownNode) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMarkdownNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateMarkdownNode) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type CreateAssetNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Placement     *Placement             `protobuf:"bytes,3,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetNode) Reset() {
	*x = CreateAssetNode{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetNode) ProtoMessage() {}

func (x *CreateAssetNode) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetNode.ProtoReflect.Descriptor instead.
func (*CreateAssetNode) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{18}
}

func (x *CreateAssetNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateAssetNode) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreateAssetNode) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

type CreateFrameNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FrameData     *FrameData             `protobuf:"bytes,2,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	Placement     *Placement             `protobuf:"bytes,3,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFrameNode) Reset() {
	*x = CreateFrameNode{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFrameNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFrameNode) ProtoMessage() {}

func (x *CreateFrameNode) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFrameNode.ProtoReflect.Descriptor instead.
func (*CreateFrameNode) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{19}
}

func (x *CreateFrameNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateFrameNode) GetFrameData() *FrameData {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *CreateFrameNode) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

type UpdateFrameNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFrameNode) Reset() {
	*x = UpdateFrameNode{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFrameNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFrameNode) ProtoMessage() {}

func (x *UpdateFrameNode) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFrameNode.ProtoReflect.Descriptor instead.
func (*UpdateFrameNode) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateFrameNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateFrameNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteNodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodes) Reset() {
	*x = DeleteNodes{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodes) ProtoMessage() {}

func (x *DeleteNodes) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodes.ProtoReflect.Descriptor instead.
func (*DeleteNodes) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteNodes) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type SetPlacements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placements    []*Placement           `protobuf:"bytes,1,rep,name=placements,proto3" json:"placements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlacements) Reset() {
	*x = SetPlacements{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlacements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlacements) ProtoMessage() {}

func (x *SetPlacements) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlacements.ProtoReflect.Descriptor instead.
func (*SetPlacements) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{22}
}

func (x *SetPlacements) GetPlacements() []*Placement {
	if x != nil {
		return x.Placements
	}
	return nil
}

type CreateConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *CanvasConnection      `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnection) Reset() {
	*x = CreateConnection{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnection) ProtoMessage() {}

func (x *CreateConnection) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnection.ProtoReflect.Descriptor instead.
func (*CreateConnection) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{23}
}

func (x *CreateConnection) GetConnection() *CanvasConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type UpdateConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *CanvasConnection      `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConnection) Reset() {
	*x = UpdateConnection{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConnection) ProtoMessage() {}

func (x *UpdateConnection) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConnection.ProtoReflect.Descriptor instead.
func (*UpdateConnection) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateConnection) GetConnection() *CanvasConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type DeleteConnections struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionIds []string               `protobuf:"bytes,1,rep,name=connection_ids,json=connectionIds,proto3" json:"connection_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnections) Reset() {
	*x = DeleteConnections{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnections) ProtoMessage() {}

func (x *DeleteConnections) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnections.ProtoReflect.Descriptor instead.
func (*DeleteConnections) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteConnections) GetConnectionIds() []string {
	if x != nil {
		return x.ConnectionIds
	}
	return nil
}

type CanvasMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*CanvasMutation_CreateMarkdownNode
	//	*CanvasMutation_UpdateMarkdownNode
	//	*CanvasMutation_CreateAssetNode
	//	*CanvasMutation_CreateFrameNode
	//	*CanvasMutation_DeleteNodes
	//	*CanvasMutation_SetPlacements
	//	*CanvasMutation_UpdateFrameNode
	//	*CanvasMutation_CreateConnection
	//	*CanvasMutation_UpdateConnection
	//	*CanvasMutation_DeleteConnections
	Value         isCanvasMutation_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasMutation) Reset() {
	*x = CanvasMutation{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasMutation) ProtoMessage() {}

func (x *CanvasMutation) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasMutation.ProtoReflect.Descriptor instead.
func (*CanvasMutation) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{26}
}

func (x *CanvasMutation) GetValue() isCanvasMutation_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CanvasMutation) GetCreateMarkdownNode() *CreateMarkdownNode {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_CreateMarkdownNode); ok {
			return x.CreateMarkdownNode
		}
	}
	return nil
}

func (x *CanvasMutation) GetUpdateMarkdownNode() *UpdateMarkdownNode {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_UpdateMarkdownNode); ok {
			return x.UpdateMarkdownNode
		}
	}
	return nil
}

func (x *CanvasMutation) GetCreateAssetNode() *CreateAssetNode {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_CreateAssetNode); ok {
			return x.CreateAssetNode
		}
	}
	return nil
}

func (x *CanvasMutation) GetCreateFrameNode() *CreateFrameNode {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_CreateFrameNode); ok {
			return x.CreateFrameNode
		}
	}
	return nil
}

func (x *CanvasMutation) GetDeleteNodes() *DeleteNodes {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_DeleteNodes); ok {
			return x.DeleteNodes
		}
	}
	return nil
}

func (x *CanvasMutation) GetSetPlacements() *SetPlacements {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_SetPlacements); ok {
			return x.SetPlacements
		}
	}
	return nil
}

func (x *CanvasMutation) GetUpdateFrameNode() *UpdateFrameNode {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_UpdateFrameNode); ok {
			return x.UpdateFrameNode
		}
	}
	return nil
}

func (x *CanvasMutation) GetCreateConnection() *CreateConnection {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_CreateConnection); ok {
			return x.CreateConnection
		}
	}
	return nil
}

func (x *CanvasMutation) GetUpdateConnection() *UpdateConnection {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_UpdateConnection); ok {
			return x.UpdateConnection
		}
	}
	return nil
}

func (x *CanvasMutation) GetDeleteConnections() *DeleteConnections {
	if x != nil {
		if x, ok := x.Value.(*CanvasMutation_DeleteConnections); ok {
			return x.DeleteConnections
		}
	}
	return nil
}

type isCanvasMutation_Value interface {
	isCanvasMutation_Value()
}

type CanvasMutation_CreateMarkdownNode struct {
	CreateMarkdownNode *CreateMarkdownNode `protobuf:"bytes,1,opt,name=create_markdown_node,json=createMarkdownNode,proto3,oneof"`
}

type CanvasMutation_UpdateMarkdownNode struct {
	UpdateMarkdownNode *UpdateMarkdownNode `protobuf:"bytes,2,opt,name=update_markdown_node,json=updateMarkdownNode,proto3,oneof"`
}

type CanvasMutation_CreateAssetNode struct {
	CreateAssetNode *CreateAssetNode `protobuf:"bytes,3,opt,name=create_asset_node,json=createAssetNode,proto3,oneof"`
}

type CanvasMutation_CreateFrameNode struct {
	CreateFrameNode *CreateFrameNode `protobuf:"bytes,4,opt,name=create_frame_node,json=createFrameNode,proto3,oneof"`
}

type CanvasMutation_DeleteNodes struct {
	DeleteNodes *DeleteNodes `protobuf:"bytes,5,opt,name=delete_nodes,json=deleteNodes,proto3,oneof"`
}

type CanvasMutation_SetPlacements struct {
	SetPlacements *SetPlacements `protobuf:"bytes,6,opt,name=set_placements,json=setPlacements,proto3,oneof"`
}

type CanvasMutation_UpdateFrameNode struct {
	UpdateFrameNode *UpdateFrameNode `protobuf:"bytes,7,opt,name=update_frame_node,json=updateFrameNode,proto3,oneof"`
}

type CanvasMutation_CreateConnection struct {
	CreateConnection *CreateConnection `protobuf:"bytes,8,opt,name=create_connection,json=createConnection,proto3,oneof"`
}

type CanvasMutation_UpdateConnection struct {
	UpdateConnection *UpdateConnection `protobuf:"bytes,9,opt,name=update_connection,json=updateConnection,proto3,oneof"`
}

type CanvasMutation_DeleteConnections struct {
	DeleteConnections *DeleteConnections `protobuf:"bytes,10,opt,name=delete_connections,json=deleteConnections,proto3,oneof"`
}

func (*CanvasMutation_CreateMarkdownNode) isCanvasMutation_Value() {}

func (*CanvasMutation_UpdateMarkdownNode) isCanvasMutation_Value() {}

func (*CanvasMutation_CreateAssetNode) isCanvasMutation_Value() {}

func (*CanvasMutation_CreateFrameNode) isCanvasMutation_Value() {}

func (*CanvasMutation_DeleteNodes) isCanvasMutation_Value() {}

func (*CanvasMutation_SetPlacements) isCanvasMutation_Value() {}

func (*CanvasMutation_UpdateFrameNode) isCanvasMutation_Value() {}

func (*CanvasMutation_CreateConnection) isCanvasMutation_Value() {}

func (*CanvasMutation_UpdateConnection) isCanvasMutation_Value() {}

func (*CanvasMutation_DeleteConnections) isCanvasMutation_Value() {}

type ApplyCanvasMutationsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectId        string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	RequestId        string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Mutations        []*CanvasMutation      `protobuf:"bytes,4,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyCanvasMutationsRequest) Reset() {
	*x = ApplyCanvasMutationsRequest{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCanvasMutationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCanvasMutationsRequest) ProtoMessage() {}

func (x *ApplyCanvasMutationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCanvasMutationsRequest.ProtoReflect.Descriptor instead.
func (*ApplyCanvasMutationsRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{27}
}

func (x *ApplyCanvasMutationsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ApplyCanvasMutationsRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ApplyCanvasMutationsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApplyCanvasMutationsRequest) GetMutations() []*CanvasMutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type CanvasRevisionConflictDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentRevision int64                  `protobuf:"varint,1,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CanvasRevisionConflictDetails) Reset() {
	*x = CanvasRevisionConflictDetails{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasRevisionConflictDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasRevisionConflictDetails) ProtoMessage() {}

func (x *CanvasRevisionConflictDetails) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasRevisionConflictDetails.ProtoReflect.Descriptor instead.
func (*CanvasRevisionConflictDetails) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{28}
}

func (x *CanvasRevisionConflictDetails) GetCurrentRevision() int64 {
	if x != nil {
		return x.CurrentRevision
	}
	return 0
}

type FieldViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{29}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ValidationDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FieldViolations []*FieldViolation      `protobuf:"bytes,1,rep,name=field_violations,json=fieldViolations,proto3" json:"field_violations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidationDetails) Reset() {
	*x = ValidationDetails{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationDetails) ProtoMessage() {}

func (x *ValidationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationDetails.ProtoReflect.Descriptor instead.
func (*ValidationDetails) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{30}
}

func (x *ValidationDetails) GetFieldViolations() []*FieldViolation {
	if x != nil {
		return x.FieldViolations
	}
	return nil
}

type RequestIdReusedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestIdReusedDetails) Reset() {
	*x = RequestIdReusedDetails{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestIdReusedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestIdReusedDetails) ProtoMessage() {}

func (x *RequestIdReusedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestIdReusedDetails.ProtoReflect.Descriptor instead.
func (*RequestIdReusedDetails) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{31}
}

func (x *RequestIdReusedDetails) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AssetNotReadyDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetNotReadyDetails) Reset() {
	*x = AssetNotReadyDetails{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetNotReadyDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetNotReadyDetails) ProtoMessage() {}

func (x *AssetNotReadyDetails) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetNotReadyDetails.ProtoReflect.Descriptor instead.
func (*AssetNotReadyDetails) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{32}
}

func (x *AssetNotReadyDetails) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetNotReadyDetails) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ApiError struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*ApiError_CanvasRevisionConflict
	//	*ApiError_Validation
	//	*ApiError_RequestIdReused
	//	*ApiError_AssetNotReady
	Details       isApiError_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiError) Reset() {
	*x = ApiError{}
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiError) ProtoMessage() {}

func (x *ApiError) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_canvas_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiError.ProtoReflect.Descriptor instead.
func (*ApiError) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_canvas_proto_rawDescGZIP(), []int{33}
}

func (x *ApiError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApiError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiError) GetDetails() isApiError_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ApiError) GetCanvasRevisionConflict() *CanvasRevisionConflictDetails {
	if x != nil {
		if x, ok := x.Details.(*ApiError_CanvasRevisionConflict); ok {
			return x.CanvasRevisionConflict
		}
	}
	return nil
}

func (x *ApiError) GetValidation() *ValidationDetails {
	if x != nil {
		if x, ok := x.Details.(*ApiError_Validation); ok {
			return x.Validation
		}
	}
	return nil
}

func (x *ApiError) GetRequestIdReused() *RequestIdReusedDetails {
	if x != nil {
		if x, ok := x.Details.(*ApiError_RequestIdReused); ok {
			return x.RequestIdReused
		}
	}
	return nil
}

func (x *ApiError) GetAssetNotReady() *AssetNotReadyDetails {
	if x != nil {
		if x, ok := x.Details.(*ApiError_AssetNotReady); ok {
			return x.AssetNotReady
		}
	}
	return nil
}

type isApiError_Details interface {
	isApiError_Details()
}

type ApiError_CanvasRevisionConflict struct {
	CanvasRevisionConflict *CanvasRevisionConflictDetails `protobuf:"bytes,3,opt,name=canvas_revision_conflict,json=canvasRevisionConflict,proto3,oneof"`
}

type ApiError_Validation struct {
	Validation *ValidationDetails `protobuf:"bytes,4,opt,name=validation,proto3,oneof"`
}

type ApiError_RequestIdReused struct {
	RequestIdReused *RequestIdReusedDetails `protobuf:"bytes,5,opt,name=request_id_reused,json=requestIdReused,proto3,oneof"`
}

type ApiError_AssetNotReady struct {
	AssetNotReady *AssetNotReadyDetails `protobuf:"bytes,6,opt,name=asset_not_ready,json=assetNotReady,proto3,oneof"`
}

func (*ApiError_CanvasRevisionConflict) isApiError_Details() {}

func (*ApiError_Validation) isApiError_Details() {}

func (*ApiError_RequestIdReused) isApiError_Details() {}

func (*ApiError_AssetNotReady) isApiError_Details() {}

var File_dreamweave_v1_canvas_proto protoreflect.FileDescriptor

const file_dreamweave_v1_canvas_proto_rawDesc = "" +
	"\n" +
	"\x1adreamweave/v1/canvas.proto\x12\rdreamweave.v1\x1a\x1cgoogle/api/annotations.proto\"\x87\x01\n" +
	"\tPlacement\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x01R\x06height\x12\x17\n" +
	"\az_index\x18\x06 \x01(\x05R\x06zIndex\"\xf0\x02\n" +
	"\x10CanvasConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\x12#\n" +
	"\rsource_handle\x18\x03 \x01(\tR\fsourceHandle\x12$\n" +
	"\x0etarget_node_id\x18\x04 \x01(\tR\ftargetNodeId\x12#\n" +
	"\rtarget_handle\x18\x05 \x01(\tR\ftargetHandle\x12\x14\n" +
	"\x05shape\x18\x06 \x01(\tR\x05shape\x12\x16\n" +
	"\x06stroke\x18\a \x01(\tR\x06stroke\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12\x19\n" +
	"\bsource_x\x18\t \x01(\x01R\asourceX\x12\x19\n" +
	"\bsource_y\x18\n" +
	" \x01(\x01R\asourceY\x12\x19\n" +
	"\btarget_x\x18\v \x01(\x01R\atargetX\x12\x19\n" +
	"\btarget_y\x18\f \x01(\x01R\atargetY\"Y\n" +
	"\tFrameData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"1\n" +
	"\x10GetCanvasRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"0\n" +
	"\x12MarkdownRenderData\x12\x1a\n" +
	"\bmarkdown\x18\x01 \x01(\tR\bmarkdown\"V\n" +
	"\x0fImageRenderData\x12+\n" +
	"\x11preview_available\x18\x01 \x01(\bR\x10previewAvailable\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\x87\x01\n" +
	"\x0fAudioRenderData\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12\x1a\n" +
	"\bwaveform\x18\x03 \x03(\x01R\bwaveform\x12\x1f\n" +
	"\vscene_label\x18\x04 \x01(\tR\n" +
	"sceneLabel\"|\n" +
	"\x0fVideoRenderData\x12)\n" +
	"\x10poster_available\x18\x01 \x01(\bR\x0fposterAvailable\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"shot_label\x18\x03 \x01(\tR\tshotLabel\"A\n" +
	"\rWebRenderData\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"embeddable\x18\x02 \x01(\bR\n" +
	"embeddable\"=\n" +
	"\x0eHtmlRenderData\x12+\n" +
	"\x11preview_available\x18\x01 \x01(\bR\x10previewAvailable\"<\n" +
	"\rPdfRenderData\x12+\n" +
	"\x11preview_available\x18\x01 \x01(\bR\x10previewAvailable\"}\n" +
	"\x10OfficeRenderData\x12\x1f\n" +
	"\voffice_kind\x18\x01 \x01(\tR\n" +
	"officeKind\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\x12+\n" +
	"\x11preview_available\x18\x03 \x01(\bR\x10previewAvailable\"I\n" +
	"\x0fFrameRenderData\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"\x99\x04\n" +
	"\n" +
	"RenderData\x12?\n" +
	"\bmarkdown\x18\x01 \x01(\v2!.dreamweave.v1.MarkdownRenderDataH\x00R\bmarkdown\x126\n" +
	"\x05image\x18\x02 \x01(\v2\x1e.dreamweave.v1.ImageRenderDataH\x00R\x05image\x126\n" +
	"\x05audio\x18\x03 \x01(\v2\x1e.dreamweave.v1.AudioRenderDataH\x00R\x05audio\x126\n" +
	"\x05video\x18\x04 \x01(\v2\x1e.dreamweave.v1.VideoRenderDataH\x00R\x05video\x12?\n" +
	"\vweb_preview\x18\x05 \x01(\v2\x1c.dreamweave.v1.WebRenderDataH\x00R\n" +
	"webPreview\x123\n" +
	"\x04html\x18\x06 \x01(\v2\x1d.dreamweave.v1.HtmlRenderDataH\x00R\x04html\x120\n" +
	"\x03pdf\x18\a \x01(\v2\x1c.dreamweave.v1.PdfRenderDataH\x00R\x03pdf\x129\n" +
	"\x06office\x18\b \x01(\v2\x1f.dreamweave.v1.OfficeRenderDataH\x00R\x06office\x126\n" +
	"\x05frame\x18\n" +
	" \x01(\v2\x1e.dreamweave.v1.FrameRenderDataH\x00R\x05frameB\a\n" +
	"\x05value\"\xfd\x01\n" +
	"\x12CanvasNodeSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x19\n" +
	"\basset_id\x18\x05 \x01(\tR\aassetId\x12:\n" +
	"\vrender_data\x18\x06 \x01(\v2\x19.dreamweave.v1.RenderDataR\n" +
	"renderData\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x89\x02\n" +
	"\x16CanvasDocumentSnapshot\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x127\n" +
	"\x05nodes\x18\x03 \x03(\v2!.dreamweave.v1.CanvasNodeSnapshotR\x05nodes\x128\n" +
	"\n" +
	"placements\x18\x04 \x03(\v2\x18.dreamweave.v1.PlacementR\n" +
	"placements\x12A\n" +
	"\vconnections\x18\x05 \x03(\v2\x1f.dreamweave.v1.CanvasConnectionR\vconnections\"\x81\x01\n" +
	"\x12CreateMarkdownNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\tR\bmarkdown\x126\n" +
	"\tplacement\x18\x03 \x01(\v2\x18.dreamweave.v1.PlacementR\tplacement\"I\n" +
	"\x12UpdateMarkdownNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\tR\bmarkdown\"}\n" +
	"\x0fCreateAssetNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x126\n" +
	"\tplacement\x18\x03 \x01(\v2\x18.dreamweave.v1.PlacementR\tplacement\"\x9b\x01\n" +
	"\x0fCreateFrameNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x127\n" +
	"\n" +
	"frame_data\x18\x02 \x01(\v2\x18.dreamweave.v1.FrameDataR\tframeData\x126\n" +
	"\tplacement\x18\x03 \x01(\v2\x18.dreamweave.v1.PlacementR\tplacement\"@\n" +
	"\x0fUpdateFrameNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"(\n" +
	"\vDeleteNodes\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\"I\n" +
	"\rSetPlacements\x128\n" +
	"\n" +
	"placements\x18\x01 \x03(\v2\x18.dreamweave.v1.PlacementR\n" +
	"placements\"S\n" +
	"\x10CreateConnection\x12?\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x1f.dreamweave.v1.CanvasConnectionR\n" +
	"connection\"S\n" +
	"\x10UpdateConnection\x12?\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x1f.dreamweave.v1.CanvasConnectionR\n" +
	"connection\":\n" +
	"\x11DeleteConnections\x12%\n" +
	"\x0econnection_ids\x18\x01 \x03(\tR\rconnectionIds\"\xac\x06\n" +
	"\x0eCanvasMutation\x12U\n" +
	"\x14create_markdown_node\x18\x01 \x01(\v2!.dreamweave.v1.CreateMarkdownNodeH\x00R\x12createMarkdownNode\x12U\n" +
	"\x14update_markdown_node\x18\x02 \x01(\v2!.dreamweave.v1.UpdateMarkdownNodeH\x00R\x12updateMarkdownNode\x12L\n" +
	"\x11create_asset_node\x18\x03 \x01(\v2\x1e.dreamweave.v1.CreateAssetNodeH\x00R\x0fcreateAssetNode\x12L\n" +
	"\x11create_frame_node\x18\x04 \x01(\v2\x1e.dreamweave.v1.CreateFrameNodeH\x00R\x0fcreateFrameNode\x12?\n" +
	"\fdelete_nodes\x18\x05 \x01(\v2\x1a.dreamweave.v1.DeleteNodesH\x00R\vdeleteNodes\x12E\n" +
	"\x0eset_placements\x18\x06 \x01(\v2\x1c.dreamweave.v1.SetPlacementsH\x00R\rsetPlacements\x12L\n" +
	"\x11update_frame_node\x18\a \x01(\v2\x1e.dreamweave.v1.UpdateFrameNodeH\x00R\x0fupdateFrameNode\x12N\n" +
	"\x11create_connection\x18\b \x01(\v2\x1f.dreamweave.v1.CreateConnectionH\x00R\x10createConnection\x12N\n" +
	"\x11update_connection\x18\t \x01(\v2\x1f.dreamweave.v1.UpdateConnectionH\x00R\x10updateConnection\x12Q\n" +
	"\x12delete_connections\x18\n" +
	" \x01(\v2 .dreamweave.v1.DeleteConnectionsH\x00R\x11deleteConnectionsB\a\n" +
	"\x05value\"\xc5\x01\n" +
	"\x1bApplyCanvasMutationsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x03R\x10expectedRevision\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12;\n" +
	"\tmutations\x18\x04 \x03(\v2\x1d.dreamweave.v1.CanvasMutationR\tmutations\"J\n" +
	"\x1dCanvasRevisionConflictDetails\x12)\n" +
	"\x10current_revision\x18\x01 \x01(\x03R\x0fcurrentRevision\">\n" +
	"\x0eFieldViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\x11ValidationDetails\x12H\n" +
	"\x10field_violations\x18\x01 \x03(\v2\x1d.dreamweave.v1.FieldViolationR\x0ffieldViolations\"7\n" +
	"\x16RequestIdReusedDetails\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"G\n" +
	"\x14AssetNotReadyDetails\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\x95\x03\n" +
	"\bApiError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12h\n" +
	"\x18canvas_revision_conflict\x18\x03 \x01(\v2,.dreamweave.v1.CanvasRevisionConflictDetailsH\x00R\x16canvasRevisionConflict\x12B\n" +
	"\n" +
	"validation\x18\x04 \x01(\v2 .dreamweave.v1.ValidationDetailsH\x00R\n" +
	"validation\x12S\n" +
	"\x11request_id_reused\x18\x05 \x01(\v2%.dreamweave.v1.RequestIdReusedDetailsH\x00R\x0frequestIdReused\x12M\n" +
	"\x0fasset_not_ready\x18\x06 \x01(\v2#.dreamweave.v1.AssetNotReadyDetailsH\x00R\rassetNotReadyB\t\n" +
	"\adetails2\xcf\x02\n" +
	"\rCanvasService\x12\x8c\x01\n" +
	"\tGetCanvas\x12\x1f.dreamweave.v1.GetCanvasRequest\x1a%.dreamweave.v1.CanvasDocumentSnapshot\"7\x82\xd3\xe4\x93\x021\x12//api/dreamweave/v1/projects/{project_id}/canvas\x12\xae\x01\n" +
	"\x14ApplyCanvasMutations\x12*.dreamweave.v1.ApplyCanvasMutationsRequest\x1a%.dreamweave.v1.CanvasDocumentSnapshot\"C\x82\xd3\xe4\x93\x02=:\x01*\"8/api/dreamweave/v1/projects/{project_id}/canvas/commandsBEZCgithub.com/dream-weave/dream-weave/apps/server/api/dreamweave/v1;v1b\x06proto3"

var (
	file_dreamweave_v1_canvas_proto_rawDescOnce sync.Once
	file_dreamweave_v1_canvas_proto_rawDescData []byte
)

func file_dreamweave_v1_canvas_proto_rawDescGZIP() []byte {
	file_dreamweave_v1_canvas_proto_rawDescOnce.Do(func() {
		file_dreamweave_v1_canvas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dreamweave_v1_canvas_proto_rawDesc), len(file_dreamweave_v1_canvas_proto_rawDesc)))
	})
	return file_dreamweave_v1_canvas_proto_rawDescData
}

var file_dreamweave_v1_canvas_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_dreamweave_v1_canvas_proto_goTypes = []any{
	(*Placement)(nil),                     // 0: dreamweave.v1.Placement
	(*CanvasConnection)(nil),              // 1: dreamweave.v1.CanvasConnection
	(*FrameData)(nil),                     // 2: dreamweave.v1.FrameData
	(*GetCanvasRequest)(nil),              // 3: dreamweave.v1.GetCanvasRequest
	(*MarkdownRenderData)(nil),            // 4: dreamweave.v1.MarkdownRenderData
	(*ImageRenderData)(nil),               // 5: dreamweave.v1.ImageRenderData
	(*AudioRenderData)(nil),               // 6: dreamweave.v1.AudioRenderData
	(*VideoRenderData)(nil),               // 7: dreamweave.v1.VideoRenderData
	(*WebRenderData)(nil),                 // 8: dreamweave.v1.WebRenderData
	(*HtmlRenderData)(nil),                // 9: dreamweave.v1.HtmlRenderData
	(*PdfRenderData)(nil),                 // 10: dreamweave.v1.PdfRenderData
	(*OfficeRenderData)(nil),              // 11: dreamweave.v1.OfficeRenderData
	(*FrameRenderData)(nil),               // 12: dreamweave.v1.FrameRenderData
	(*RenderData)(nil),                    // 13: dreamweave.v1.RenderData
	(*CanvasNodeSnapshot)(nil),            // 14: dreamweave.v1.CanvasNodeSnapshot
	(*CanvasDocumentSnapshot)(nil),        // 15: dreamweave.v1.CanvasDocumentSnapshot
	(*CreateMarkdownNode)(nil),            // 16: dreamweave.v1.CreateMarkdownNode
	(*UpdateMarkdownNode)(nil),            // 17: dreamweave.v1.UpdateMarkdownNode
	(*CreateAssetNode)(nil),               // 18: dreamweave.v1.CreateAssetNode
	(*CreateFrameNode)(nil),               // 19: dreamweave.v1.CreateFrameNode
	(*UpdateFrameNode)(nil),               // 20: dreamweave.v1.UpdateFrameNode
	(*DeleteNodes)(nil),                   // 21: dreamweave.v1.DeleteNodes
	(*SetPlacements)(nil),                 // 22: dreamweave.v1.SetPlacements
	(*CreateConnection)(nil),              // 23: dreamweave.v1.CreateConnection
	(*UpdateConnection)(nil),              // 24: dreamweave.v1.UpdateConnection
	(*DeleteConnections)(nil),             // 25: dreamweave.v1.DeleteConnections
	(*CanvasMutation)(nil),                // 26: dreamweave.v1.CanvasMutation
	(*ApplyCanvasMutationsRequest)(nil),   // 27: dreamweave.v1.ApplyCanvasMutationsRequest
	(*CanvasRevisionConflictDetails)(nil), // 28: dreamweave.v1.CanvasRevisionConflictDetails
	(*FieldViolation)(nil),                // 29: dreamweave.v1.FieldViolation
	(*ValidationDetails)(nil),             // 30: dreamweave.v1.ValidationDetails
	(*RequestIdReusedDetails)(nil),        // 31: dreamweave.v1.RequestIdReusedDetails
	(*AssetNotReadyDetails)(nil),          // 32: dreamweave.v1.AssetNotReadyDetails
	(*ApiError)(nil),                      // 33: dreamweave.v1.ApiError
}
var file_dreamweave_v1_canvas_proto_depIdxs = []int32{
	4,  // 0: dreamweave.v1.RenderData.markdown:type_name -> dreamweave.v1.MarkdownRenderData
	5,  // 1: dreamweave.v1.RenderData.image:type_name -> dreamweave.v1.ImageRenderData
	6,  // 2: dreamweave.v1.RenderData.audio:type_name -> dreamweave.v1.AudioRenderData
	7,  // 3: dreamweave.v1.RenderData.video:type_name -> dreamweave.v1.VideoRenderData
	8,  // 4: dreamweave.v1.RenderData.web_preview:type_name -> dreamweave.v1.WebRenderData
	9,  // 5: dreamweave.v1.RenderData.html:type_name -> dreamweave.v1.HtmlRenderData
	10, // 6: dreamweave.v1.RenderData.pdf:type_name -> dreamweave.v1.PdfRenderData
	11, // 7: dreamweave.v1.RenderData.office:type_name -> dreamweave.v1.OfficeRenderData
	12, // 8: dreamweave.v1.RenderData.frame:type_name -> dreamweave.v1.FrameRenderData
	13, // 9: dreamweave.v1.CanvasNodeSnapshot.render_data:type_name -> dreamweave.v1.RenderData
	14, // 10: dreamweave.v1.CanvasDocumentSnapshot.nodes:type_name -> dreamweave.v1.CanvasNodeSnapshot
	0,  // 11: dreamweave.v1.CanvasDocumentSnapshot.placements:type_name -> dreamweave.v1.Placement
	1,  // 12: dreamweave.v1.CanvasDocumentSnapshot.connections:type_name -> dreamweave.v1.CanvasConnection
	0,  // 13: dreamweave.v1.CreateMarkdownNode.placement:type_name -> dreamweave.v1.Placement
	0,  // 14: dreamweave.v1.CreateAssetNode.placement:type_name -> dreamweave.v1.Placement
	2,  // 15: dreamweave.v1.CreateFrameNode.frame_data:type_name -> dreamweave.v1.FrameData
	0,  // 16: dreamweave.v1.CreateFrameNode.placement:type_name -> dreamweave.v1.Placement
	0,  // 17: dreamweave.v1.SetPlacements.placements:type_name -> dreamweave.v1.Placement
	1,  // 18: dreamweave.v1.CreateConnection.connection:type_name -> dreamweave.v1.CanvasConnection
	1,  // 19: dreamweave.v1.UpdateConnection.connection:type_name -> dreamweave.v1.CanvasConnection
	16, // 20: dreamweave.v1.CanvasMutation.create_markdown_node:type_name -> dreamweave.v1.CreateMarkdownNode
	17, // 21: dreamweave.v1.CanvasMutation.update_markdown_node:type_name -> dreamweave.v1.UpdateMarkdownNode
	18, // 22: dreamweave.v1.CanvasMutation.create_asset_node:type_name -> dreamweave.v1.CreateAssetNode
	19, // 23: dreamweave.v1.CanvasMutation.create_frame_node:type_name -> dreamweave.v1.CreateFrameNode
	21, // 24: dreamweave.v1.CanvasMutation.delete_nodes:type_name -> dreamweave.v1.DeleteNodes
	22, // 25: dreamweave.v1.CanvasMutation.set_placements:type_name -> dreamweave.v1.SetPlacements
	20, // 26: dreamweave.v1.CanvasMutation.update_frame_node:type_name -> dreamweave.v1.UpdateFrameNode
	23, // 27: dreamweave.v1.CanvasMutation.create_connection:type_name -> dreamweave.v1.CreateConnection
	24, // 28: dreamweave.v1.CanvasMutation.update_connection:type_name -> dreamweave.v1.UpdateConnection
	25, // 29: dreamweave.v1.CanvasMutation.delete_connections:type_name -> dreamweave.v1.DeleteConnections
	26, // 30: dreamweave.v1.ApplyCanvasMutationsRequest.mutations:type_name -> dreamweave.v1.CanvasMutation
	29, // 31: dreamweave.v1.ValidationDetails.field_violations:type_name -> dreamweave.v1.FieldViolation
	28, // 32: dreamweave.v1.ApiError.canvas_revision_conflict:type_name -> dreamweave.v1.CanvasRevisionConflictDetails
	30, // 33: dreamweave.v1.ApiError.validation:type_name -> dreamweave.v1.ValidationDetails
	31, // 34: dreamweave.v1.ApiError.request_id_reused:type_name -> dreamweave.v1.RequestIdReusedDetails
	32, // 35: dreamweave.v1.ApiError.asset_not_ready:type_name -> dreamweave.v1.AssetNotReadyDetails
	3,  // 36: dreamweave.v1.CanvasService.GetCanvas:input_type -> dreamweave.v1.GetCanvasRequest
	27, // 37: dreamweave.v1.CanvasService.ApplyCanvasMutations:input_type -> dreamweave.v1.ApplyCanvasMutationsRequest
	15, // 38: dreamweave.v1.CanvasService.GetCanvas:output_type -> dreamweave.v1.CanvasDocumentSnapshot
	15, // 39: dreamweave.v1.CanvasService.ApplyCanvasMutations:output_type -> dreamweave.v1.CanvasDocumentSnapshot
	38, // [38:40] is the sub-list for method output_type
	36, // [36:38] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_dreamweave_v1_canvas_proto_init() }
func file_dreamweave_v1_canvas_proto_init() {
	if File_dreamweave_v1_canvas_proto != nil {
		return
	}
	file_dreamweave_v1_canvas_proto_msgTypes[13].OneofWrappers = []any{
		(*RenderData_Markdown)(nil),
		(*RenderData_Image)(nil),
		(*RenderData_Audio)(nil),
		(*RenderData_Video)(nil),
		(*RenderData_WebPreview)(nil),
		(*RenderData_Html)(nil),
		(*RenderData_Pdf)(nil),
		(*RenderData_Office)(nil),
		(*RenderData_Frame)(nil),
	}
	file_dreamweave_v1_canvas_proto_msgTypes[26].OneofWrappers = []any{
		(*CanvasMutation_CreateMarkdownNode)(nil),
		(*CanvasMutation_UpdateMarkdownNode)(nil),
		(*CanvasMutation_CreateAssetNode)(nil),
		(*CanvasMutation_CreateFrameNode)(nil),
		(*CanvasMutation_DeleteNodes)(nil),
		(*CanvasMutation_SetPlacements)(nil),
		(*CanvasMutation_UpdateFrameNode)(nil),
		(*CanvasMutation_CreateConnection)(nil),
		(*CanvasMutation_UpdateConnection)(nil),
		(*CanvasMutation_DeleteConnections)(nil),
	}
	file_dreamweave_v1_canvas_proto_msgTypes[33].OneofWrappers = []any{
		(*ApiError_CanvasRevisionConflict)(nil),
		(*ApiError_Validation)(nil),
		(*ApiError_RequestIdReused)(nil),
		(*ApiError_AssetNotReady)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dreamweave_v1_canvas_proto_rawDesc), len(file_dreamweave_v1_canvas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dreamweave_v1_canvas_proto_goTypes,
		DependencyIndexes: file_dreamweave_v1_canvas_proto_depIdxs,
		MessageInfos:      file_dreamweave_v1_canvas_proto_msgTypes,
	}.Build()
	File_dreamweave_v1_canvas_proto = out.File
	file_dreamweave_v1_canvas_proto_goTypes = nil
	file_dreamweave_v1_canvas_proto_depIdxs = nil
}
