// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dreamweave/v1/canvas.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CanvasService_GetCanvas_FullMethodName            = "/dreamweave.v1.CanvasService/GetCanvas"
	CanvasService_ApplyCanvasMutations_FullMethodName = "/dreamweave.v1.CanvasService/ApplyCanvasMutations"
)

// CanvasServiceClient is the client API for CanvasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CanvasServiceClient interface {
	GetCanvas(ctx context.Context, in *GetCanvasRequest, opts ...grpc.CallOption) (*CanvasDocumentSnapshot, error)
	ApplyCanvasMutations(ctx context.Context, in *ApplyCanvasMutationsRequest, opts ...grpc.CallOption) (*CanvasDocumentSnapshot, error)
}

type canvasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCanvasServiceClient(cc grpc.ClientConnInterface) CanvasServiceClient {
	return &canvasServiceClient{cc}
}

func (c *canvasServiceClient) GetCanvas(ctx context.Context, in *GetCanvasRequest, opts ...grpc.CallOption) (*CanvasDocumentSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanvasDocumentSnapshot)
	err := c.cc.Invoke(ctx, CanvasService_GetCanvas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasServiceClient) ApplyCanvasMutations(ctx context.Context, in *ApplyCanvasMutationsRequest, opts ...grpc.CallOption) (*CanvasDocumentSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanvasDocumentSnapshot)
	err := c.cc.Invoke(ctx, CanvasService_ApplyCanvasMutations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CanvasServiceServer is the server API for CanvasService service.
// All implementations must embed UnimplementedCanvasServiceServer
// for forward compatibility.
type CanvasServiceServer interface {
	GetCanvas(context.Context, *GetCanvasRequest) (*CanvasDocumentSnapshot, error)
	ApplyCanvasMutations(context.Context, *ApplyCanvasMutationsRequest) (*CanvasDocumentSnapshot, error)
	mustEmbedUnimplementedCanvasServiceServer()
}

// UnimplementedCanvasServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCanvasServiceServer struct{}

func (UnimplementedCanvasServiceServer) GetCanvas(context.Context, *GetCanvasRequest) (*CanvasDocumentSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCanvas not implemented")
}
func (UnimplementedCanvasServiceServer) ApplyCanvasMutations(context.Context, *ApplyCanvasMutationsRequest) (*CanvasDocumentSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCanvasMutations not implemented")
}
func (UnimplementedCanvasServiceServer) mustEmbedUnimplementedCanvasServiceServer() {}
func (UnimplementedCanvasServiceServer) testEmbeddedByValue()                       {}

// UnsafeCanvasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CanvasServiceServer will
// result in compilation errors.
type UnsafeCanvasServiceServer interface {
	mustEmbedUnimplementedCanvasServiceServer()
}

func RegisterCanvasServiceServer(s grpc.ServiceRegistrar, srv CanvasServiceServer) {
	// If the following call panics, it indicates UnimplementedCanvasServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CanvasService_ServiceDesc, srv)
}

func _CanvasService_GetCanvas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCanvasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasServiceServer).GetCanvas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasService_GetCanvas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasServiceServer).GetCanvas(ctx, req.(*GetCanvasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasService_ApplyCanvasMutations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCanvasMutationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasServiceServer).ApplyCanvasMutations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasService_ApplyCanvasMutations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasServiceServer).ApplyCanvasMutations(ctx, req.(*ApplyCanvasMutationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CanvasService_ServiceDesc is the grpc.ServiceDesc for CanvasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CanvasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dreamweave.v1.CanvasService",
	HandlerType: (*CanvasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCanvas",
			Handler:    _CanvasService_GetCanvas_Handler,
		},
		{
			MethodName: "ApplyCanvasMutations",
			Handler:    _CanvasService_ApplyCanvasMutations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dreamweave/v1/canvas.proto",
}
