// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: dreamweave/v1/canvas.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCanvasServiceApplyCanvasMutations = "/dreamweave.v1.CanvasService/ApplyCanvasMutations"
const OperationCanvasServiceGetCanvas = "/dreamweave.v1.CanvasService/GetCanvas"

type CanvasServiceHTTPServer interface {
	ApplyCanvasMutations(context.Context, *ApplyCanvasMutationsRequest) (*CanvasDocumentSnapshot, error)
	GetCanvas(context.Context, *GetCanvasRequest) (*CanvasDocumentSnapshot, error)
}

func RegisterCanvasServiceHTTPServer(s *http.Server, srv CanvasServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/dreamweave/v1/projects/{project_id}/canvas", _CanvasService_GetCanvas0_HTTP_Handler(srv))
	r.POST("/api/dreamweave/v1/projects/{project_id}/canvas/commands", _CanvasService_ApplyCanvasMutations0_HTTP_Handler(srv))
}

func _CanvasService_GetCanvas0_HTTP_Handler(srv CanvasServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCanvasRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCanvasServiceGetCanvas)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCanvas(ctx, req.(*GetCanvasRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CanvasDocumentSnapshot)
		return ctx.Result(200, reply)
	}
}

func _CanvasService_ApplyCanvasMutations0_HTTP_Handler(srv CanvasServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyCanvasMutationsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCanvasServiceApplyCanvasMutations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyCanvasMutations(ctx, req.(*ApplyCanvasMutationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CanvasDocumentSnapshot)
		return ctx.Result(200, reply)
	}
}

type CanvasServiceHTTPClient interface {
	ApplyCanvasMutations(ctx context.Context, req *ApplyCanvasMutationsRequest, opts ...http.CallOption) (rsp *CanvasDocumentSnapshot, err error)
	GetCanvas(ctx context.Context, req *GetCanvasRequest, opts ...http.CallOption) (rsp *CanvasDocumentSnapshot, err error)
}

type CanvasServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCanvasServiceHTTPClient(client *http.Client) CanvasServiceHTTPClient {
	return &CanvasServiceHTTPClientImpl{client}
}

func (c *CanvasServiceHTTPClientImpl) ApplyCanvasMutations(ctx context.Context, in *ApplyCanvasMutationsRequest, opts ...http.CallOption) (*CanvasDocumentSnapshot, error) {
	var out CanvasDocumentSnapshot
	pattern := "/api/dreamweave/v1/projects/{project_id}/canvas/commands"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCanvasServiceApplyCanvasMutations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CanvasServiceHTTPClientImpl) GetCanvas(ctx context.Context, in *GetCanvasRequest, opts ...http.CallOption) (*CanvasDocumentSnapshot, error) {
	var out CanvasDocumentSnapshot
	pattern := "/api/dreamweave/v1/projects/{project_id}/canvas"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCanvasServiceGetCanvas))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
