// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: dreamweave/v1/office.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOfficeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfficeSessionRequest) Reset() {
	*x = CreateOfficeSessionRequest{}
	mi := &file_dreamweave_v1_office_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfficeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfficeSessionRequest) ProtoMessage() {}

func (x *CreateOfficeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_office_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfficeSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateOfficeSessionRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_office_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOfficeSessionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateOfficeSessionRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type OfficeViewerSessionRuntimeConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DocumentServerUrl string                 `protobuf:"bytes,2,opt,name=document_server_url,json=documentServerUrl,proto3" json:"document_server_url,omitempty"`
	DocumentUrl       string                 `protobuf:"bytes,3,opt,name=document_url,json=documentUrl,proto3" json:"document_url,omitempty"`
	DocumentKey       string                 `protobuf:"bytes,4,opt,name=document_key,json=documentKey,proto3" json:"document_key,omitempty"`
	Token             string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	DocumentTitle     string                 `protobuf:"bytes,6,opt,name=document_title,json=documentTitle,proto3" json:"document_title,omitempty"`
	FileType          string                 `protobuf:"bytes,7,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	DocumentType      string                 `protobuf:"bytes,8,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	ExpiresAt         string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OfficeViewerSessionRuntimeConfig) Reset() {
	*x = OfficeViewerSessionRuntimeConfig{}
	mi := &file_dreamweave_v1_office_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfficeViewerSessionRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeViewerSessionRuntimeConfig) ProtoMessage() {}

func (x *OfficeViewerSessionRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_office_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeViewerSessionRuntimeConfig.ProtoReflect.Descriptor instead.
func (*OfficeViewerSessionRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_office_proto_rawDescGZIP(), []int{1}
}

func (x *OfficeViewerSessionRuntimeConfig) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OfficeViewerSessionRuntimeConfig) GetDocumentServerUrl() string {
	if x != nil {
		return x.DocumentServerUrl
	}
	return ""
}

func (x *OfficeViewerSessionRuntimeConfig) GetDocumentUrl() string {
	if x != nil {
		return x.DocumentUrl
	}
	return ""
}

func (x *OfficeViewerSessionRuntimeConfig) GetDocumentKey() string {
	if x != nil {
		return x.DocumentKey
	}
	return ""
}

func (x *OfficeViewerSessionRuntimeConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OfficeViewerSessionRuntimeConfig) GetDocumentTitle() string {
	if x != nil {
		return x.DocumentTitle
	}
	return ""
}

func (x *OfficeViewerSessionRuntimeConfig) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *OfficeViewerSessionRuntimeConfig) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *OfficeViewerSessionRuntimeConfig) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_dreamweave_v1_office_proto protoreflect.FileDescriptor

const file_dreamweave_v1_office_proto_rawDesc = "" +
	"\n" +
	"\x1adreamweave/v1/office.proto\x12\rdreamweave.v1\x1a\x1cgoogle/api/annotations.proto\"V\n" +
	"\x1aCreateOfficeSessionRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"\xd5\x02\n" +
	" OfficeViewerSessionRuntimeConfig\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12.\n" +
	"\x13document_server_url\x18\x02 \x01(\tR\x11documentServerUrl\x12!\n" +
	"\fdocument_url\x18\x03 \x01(\tR\vdocumentUrl\x12!\n" +
	"\fdocument_key\x18\x04 \x01(\tR\vdocumentKey\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12%\n" +
	"\x0edocument_title\x18\x06 \x01(\tR\rdocumentTitle\x12\x1b\n" +
	"\tfile_type\x18\a \x01(\tR\bfileType\x12#\n" +
	"\rdocument_type\x18\b \x01(\tR\fdocumentType\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt2\xda\x01\n" +
	"\rOfficeService\x12\xc8\x01\n" +
	"\x13CreateOfficeSession\x12).dreamweave.v1.CreateOfficeSessionRequest\x1a/.dreamweave.v1.OfficeViewerSessionRuntimeConfig\"U\x82\xd3\xe4\x93\x02O:\x01*\"J/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/office-sessionsBEZCgithub.com/dream-weave/dream-weave/apps/server/api/dreamweave/v1;v1b\x06proto3"

var (
	file_dreamweave_v1_office_proto_rawDescOnce sync.Once
	file_dreamweave_v1_office_proto_rawDescData []byte
)

func file_dreamweave_v1_office_proto_rawDescGZIP() []byte {
	file_dreamweave_v1_office_proto_rawDescOnce.Do(func() {
		file_dreamweave_v1_office_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dreamweave_v1_office_proto_rawDesc), len(file_dreamweave_v1_office_proto_rawDesc)))
	})
	return file_dreamweave_v1_office_proto_rawDescData
}

var file_dreamweave_v1_office_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dreamweave_v1_office_proto_goTypes = []any{
	(*CreateOfficeSessionRequest)(nil),       // 0: dreamweave.v1.CreateOfficeSessionRequest
	(*OfficeViewerSessionRuntimeConfig)(nil), // 1: dreamweave.v1.OfficeViewerSessionRuntimeConfig
}
var file_dreamweave_v1_office_proto_depIdxs = []int32{
	0, // 0: dreamweave.v1.OfficeService.CreateOfficeSession:input_type -> dreamweave.v1.CreateOfficeSessionRequest
	1, // 1: dreamweave.v1.OfficeService.CreateOfficeSession:output_type -> dreamweave.v1.OfficeViewerSessionRuntimeConfig
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dreamweave_v1_office_proto_init() }
func file_dreamweave_v1_office_proto_init() {
	if File_dreamweave_v1_office_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dreamweave_v1_office_proto_rawDesc), len(file_dreamweave_v1_office_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dreamweave_v1_office_proto_goTypes,
		DependencyIndexes: file_dreamweave_v1_office_proto_depIdxs,
		MessageInfos:      file_dreamweave_v1_office_proto_msgTypes,
	}.Build()
	File_dreamweave_v1_office_proto = out.File
	file_dreamweave_v1_office_proto_goTypes = nil
	file_dreamweave_v1_office_proto_depIdxs = nil
}
