// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: dreamweave/v1/office.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOfficeServiceCreateOfficeSession = "/dreamweave.v1.OfficeService/CreateOfficeSession"

type OfficeServiceHTTPServer interface {
	CreateOfficeSession(context.Context, *CreateOfficeSessionRequest) (*OfficeViewerSessionRuntimeConfig, error)
}

func RegisterOfficeServiceHTTPServer(s *http.Server, srv OfficeServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/office-sessions", _OfficeService_CreateOfficeSession0_HTTP_Handler(srv))
}

func _OfficeService_CreateOfficeSession0_HTTP_Handler(srv OfficeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOfficeSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOfficeServiceCreateOfficeSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOfficeSession(ctx, req.(*CreateOfficeSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OfficeViewerSessionRuntimeConfig)
		return ctx.Result(200, reply)
	}
}

type OfficeServiceHTTPClient interface {
	CreateOfficeSession(ctx context.Context, req *CreateOfficeSessionRequest, opts ...http.CallOption) (rsp *OfficeViewerSessionRuntimeConfig, err error)
}

type OfficeServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOfficeServiceHTTPClient(client *http.Client) OfficeServiceHTTPClient {
	return &OfficeServiceHTTPClientImpl{client}
}

func (c *OfficeServiceHTTPClientImpl) CreateOfficeSession(ctx context.Context, in *CreateOfficeSessionRequest, opts ...http.CallOption) (*OfficeViewerSessionRuntimeConfig, error) {
	var out OfficeViewerSessionRuntimeConfig
	pattern := "/api/dreamweave/v1/projects/{project_id}/assets/{asset_id}/office-sessions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOfficeServiceCreateOfficeSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
