// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: dreamweave/v1/projects.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProjectServiceCreateProject = "/dreamweave.v1.ProjectService/CreateProject"
const OperationProjectServiceGetProject = "/dreamweave.v1.ProjectService/GetProject"
const OperationProjectServiceUpsertProjectMember = "/dreamweave.v1.ProjectService/UpsertProjectMember"

type ProjectServiceHTTPServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	GetProject(context.Context, *GetProjectRequest) (*Project, error)
	UpsertProjectMember(context.Context, *UpsertProjectMemberRequest) (*ProjectMember, error)
}

func RegisterProjectServiceHTTPServer(s *http.Server, srv ProjectServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/dreamweave/v1/projects", _ProjectService_CreateProject0_HTTP_Handler(srv))
	r.GET("/api/dreamweave/v1/projects/{project_id}", _ProjectService_GetProject0_HTTP_Handler(srv))
	r.PUT("/api/dreamweave/v1/projects/{project_id}/members/{user_id}", _ProjectService_UpsertProjectMember0_HTTP_Handler(srv))
}

func _ProjectService_CreateProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProjectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceCreateProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProject(ctx, req.(*CreateProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Project)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_GetProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProjectRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceGetProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProject(ctx, req.(*GetProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Project)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_UpsertProjectMember0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertProjectMemberRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceUpsertProjectMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertProjectMember(ctx, req.(*UpsertProjectMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProjectMember)
		return ctx.Result(200, reply)
	}
}

type ProjectServiceHTTPClient interface {
	CreateProject(ctx context.Context, req *CreateProjectRequest, opts ...http.CallOption) (rsp *Project, err error)
	GetProject(ctx context.Context, req *GetProjectRequest, opts ...http.CallOption) (rsp *Project, err error)
	UpsertProjectMember(ctx context.Context, req *UpsertProjectMemberRequest, opts ...http.CallOption) (rsp *ProjectMember, err error)
}

type ProjectServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProjectServiceHTTPClient(client *http.Client) ProjectServiceHTTPClient {
	return &ProjectServiceHTTPClientImpl{client}
}

func (c *ProjectServiceHTTPClientImpl) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...http.CallOption) (*Project, error) {
	var out Project
	pattern := "/api/dreamweave/v1/projects"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectServiceCreateProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) GetProject(ctx context.Context, in *GetProjectRequest, opts ...http.CallOption) (*Project, error) {
	var out Project
	pattern := "/api/dreamweave/v1/projects/{project_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProjectServiceGetProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) UpsertProjectMember(ctx context.Context, in *UpsertProjectMemberRequest, opts ...http.CallOption) (*ProjectMember, error) {
	var out ProjectMember
	pattern := "/api/dreamweave/v1/projects/{project_id}/members/{user_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectServiceUpsertProjectMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
