// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: dreamweave/v1/projects.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_dreamweave_v1_projects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_projects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_projects_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProjectRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_dreamweave_v1_projects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_projects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_projects_proto_rawDescGZIP(), []int{1}
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_dreamweave_v1_projects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_projects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_projects_proto_rawDescGZIP(), []int{2}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Project) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpsertProjectMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProjectMemberRequest) Reset() {
	*x = UpsertProjectMemberRequest{}
	mi := &file_dreamweave_v1_projects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProjectMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProjectMemberRequest) ProtoMessage() {}

func (x *UpsertProjectMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_projects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProjectMemberRequest.ProtoReflect.Descriptor instead.
func (*UpsertProjectMemberRequest) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_projects_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertProjectMemberRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpsertProjectMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertProjectMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ProjectMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_dreamweave_v1_projects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_dreamweave_v1_projects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_dreamweave_v1_projects_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectMember) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProjectMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_dreamweave_v1_projects_proto protoreflect.FileDescriptor

const file_dreamweave_v1_projects_proto_rawDesc = "" +
	"\n" +
	"\x1cdreamweave/v1/projects.proto\x12\rdreamweave.v1\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\x14CreateProjectRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"2\n" +
	"\x11GetProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"u\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"h\n" +
	"\x1aUpsertProjectMemberRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"[\n" +
	"\rProjectMember\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2\xa8\x03\n" +
	"\x0eProjectService\x12t\n" +
	"\rCreateProject\x12#.dreamweave.v1.CreateProjectRequest\x1a\x16.dreamweave.v1.Project\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/dreamweave/v1/projects\x12x\n" +
	"\n" +
	"GetProject\x12 .dreamweave.v1.GetProjectRequest\x1a\x16.dreamweave.v1.Project\"0\x82\xd3\xe4\x93\x02*\x12(/api/dreamweave/v1/projects/{project_id}\x12\xa5\x01\n" +
	"\x13UpsertProjectMember\x12).dreamweave.v1.UpsertProjectMemberRequest\x1a\x1c.dreamweave.v1.ProjectMember\"E\x82\xd3\xe4\x93\x02?:\x01*\x1a:/api/dreamweave/v1/projects/{project_id}/members/{user_id}BEZCgithub.com/dream-weave/dream-weave/apps/server/api/dreamweave/v1;v1b\x06proto3"

var (
	file_dreamweave_v1_projects_proto_rawDescOnce sync.Once
	file_dreamweave_v1_projects_proto_rawDescData []byte
)

func file_dreamweave_v1_projects_proto_rawDescGZIP() []byte {
	file_dreamweave_v1_projects_proto_rawDescOnce.Do(func() {
		file_dreamweave_v1_projects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dreamweave_v1_projects_proto_rawDesc), len(file_dreamweave_v1_projects_proto_rawDesc)))
	})
	return file_dreamweave_v1_projects_proto_rawDescData
}

var file_dreamweave_v1_projects_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dreamweave_v1_projects_proto_goTypes = []any{
	(*CreateProjectRequest)(nil),       // 0: dreamweave.v1.CreateProjectRequest
	(*GetProjectRequest)(nil),          // 1: dreamweave.v1.GetProjectRequest
	(*Project)(nil),                    // 2: dreamweave.v1.Project
	(*UpsertProjectMemberRequest)(nil), // 3: dreamweave.v1.UpsertProjectMemberRequest
	(*ProjectMember)(nil),              // 4: dreamweave.v1.ProjectMember
}
var file_dreamweave_v1_projects_proto_depIdxs = []int32{
	0, // 0: dreamweave.v1.ProjectService.CreateProject:input_type -> dreamweave.v1.CreateProjectRequest
	1, // 1: dreamweave.v1.ProjectService.GetProject:input_type -> dreamweave.v1.GetProjectRequest
	3, // 2: dreamweave.v1.ProjectService.UpsertProjectMember:input_type -> dreamweave.v1.UpsertProjectMemberRequest
	2, // 3: dreamweave.v1.ProjectService.CreateProject:output_type -> dreamweave.v1.Project
	2, // 4: dreamweave.v1.ProjectService.GetProject:output_type -> dreamweave.v1.Project
	4, // 5: dreamweave.v1.ProjectService.UpsertProjectMember:output_type -> dreamweave.v1.ProjectMember
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dreamweave_v1_projects_proto_init() }
func file_dreamweave_v1_projects_proto_init() {
	if File_dreamweave_v1_projects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dreamweave_v1_projects_proto_rawDesc), len(file_dreamweave_v1_projects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dreamweave_v1_projects_proto_goTypes,
		DependencyIndexes: file_dreamweave_v1_projects_proto_depIdxs,
		MessageInfos:      file_dreamweave_v1_projects_proto_msgTypes,
	}.Build()
	File_dreamweave_v1_projects_proto = out.File
	file_dreamweave_v1_projects_proto_goTypes = nil
	file_dreamweave_v1_projects_proto_depIdxs = nil
}
