// Command canonicalize-typescript-http corrects the upstream generator's
// TypeScript representation of protobuf 64-bit integers. Proto JSON encodes
// every 64-bit integer as a decimal string; the generated client must expose
// and serialize the same representation.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: canonicalize-typescript-http <descriptor.pb> <generated.ts>")
		os.Exit(2)
	}
	descriptorBytes, err := os.ReadFile(os.Args[1])
	must(err)
	set := &descriptorpb.FileDescriptorSet{}
	must(proto.Unmarshal(descriptorBytes, set))

	fields := map[string]map[string]bool{}
	for _, file := range set.GetFile() {
		if file.GetPackage() != "dreamweave.v1" {
			continue
		}
		collectMessages(fields, file.GetMessageType())
	}

	generatedBytes, err := os.ReadFile(os.Args[2])
	must(err)
	lines := strings.Split(string(generatedBytes), "\n")
	current := ""
	changed := map[string]bool{}
	for index, line := range lines {
		if strings.HasPrefix(line, "export type ") && strings.HasSuffix(line, " = {") {
			current = strings.TrimSuffix(strings.TrimPrefix(line, "export type "), " = {")
			continue
		}
		if current == "" {
			continue
		}
		if line == "};" {
			current = ""
			continue
		}
		for field := range fields[current] {
			prefix := "  " + field + ": "
			if strings.HasPrefix(line, prefix) {
				lines[index] = strings.Replace(line, "number", "string", 1)
				changed[current+"."+field] = true
			}
		}
	}

	var missing []string
	for message, messageFields := range fields {
		for field := range messageFields {
			key := message + "." + field
			if !changed[key] {
				missing = append(missing, key)
			}
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		fmt.Fprintf(os.Stderr, "generated TypeScript is missing protobuf int64 fields: %s\n", strings.Join(missing, ", "))
		os.Exit(1)
	}
	const marker = "// Proto JSON int64 fields canonicalized as decimal strings.\n"
	output := strings.Join(lines, "\n")
	output = strings.Replace(output, "// Code generated by protoc-gen-typescript-http. DO NOT EDIT.\n", "// Code generated by protoc-gen-typescript-http. DO NOT EDIT.\n"+marker, 1)
	must(os.WriteFile(os.Args[2], []byte(output), 0o644))
}

func collectMessages(result map[string]map[string]bool, messages []*descriptorpb.DescriptorProto) {
	for _, message := range messages {
		for _, field := range message.GetField() {
			if is64Bit(field.GetType()) {
				if result[message.GetName()] == nil {
					result[message.GetName()] = map[string]bool{}
				}
				result[message.GetName()][field.GetJsonName()] = true
			}
		}
		collectMessages(result, message.GetNestedType())
	}
}

func is64Bit(value descriptorpb.FieldDescriptorProto_Type) bool {
	switch value {
	case descriptorpb.FieldDescriptorProto_TYPE_INT64,
		descriptorpb.FieldDescriptorProto_TYPE_UINT64,
		descriptorpb.FieldDescriptorProto_TYPE_SINT64,
		descriptorpb.FieldDescriptorProto_TYPE_FIXED64,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED64:
		return true
	default:
		return false
	}
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
